services:
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3315:3306"
        networks:
            - laravel_network

    nginx:
        image: nginx:stable-alpine
        container_name: laravel_nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - laravel_network

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
