version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3315:3306"
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      timeout: 5s
      interval: 3s

  queue:
    image: brq-transation-app
    container_name: laravel_queue_worker
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    command: php artisan queue:work
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge